import { EventDate } from "@/types/offer";

export const islamicEvents: EventDate[] = [
  {
    name: "Ramadan",
    type: "islamic_event",
    islamicMonth: 9,
    islamicDay: 1,
    discountPercentage: 25,
    icon: "moon",
    description: "Ramadan Kareem! Special 25% discount on all services",
    durationDays: 30,
    backgroundColor: "#8B5CF6",
  },
  {
    name: "Eid al-Fitr",
    type: "islamic_event",
    islamicMonth: 10,
    islamicDay: 1,
    discountPercentage: 30,
    icon: "sparkles",
    description: "Eid Mubarak! Celebrate with 30% off",
    durationDays: 3,
    backgroundColor: "#10B981",
  },
  {
    name: "Eid al-Adha",
    type: "islamic_event",
    islamicMonth: 12,
    islamicDay: 10,
    discountPercentage: 30,
    icon: "sparkles",
    description: "Eid Mubarak! Special 30% discount",
    durationDays: 4,
    backgroundColor: "#10B981",
  },
  {
    name: "Islamic New Year",
    type: "islamic_event",
    islamicMonth: 1,
    islamicDay: 1,
    discountPercentage: 20,
    icon: "calendar",
    description: "Happy Islamic New Year! 20% off to celebrate",
    durationDays: 1,
    backgroundColor: "#6366F1",
  },
  {
    name: "Prophet's Birthday",
    type: "islamic_event",
    islamicMonth: 3,
    islamicDay: 12,
    discountPercentage: 20,
    icon: "heart",
    description: "Mawlid al-Nabi! Special 20% discount",
    durationDays: 1,
    backgroundColor: "#EC4899",
  },
];

export const egyptianHolidays: EventDate[] = [
  {
    name: "Mother's Day",
    type: "mothers_day",
    gregorianDate: "03-21",
    discountPercentage: 25,
    icon: "heart",
    description: "Celebrate Mom with 25% off! Perfect time to refresh her wardrobe",
    durationDays: 1,
    backgroundColor: "#F43F5E",
  },
  {
    name: "Revolution Day",
    type: "egyptian_holiday",
    gregorianDate: "01-25",
    discountPercentage: 15,
    icon: "flag",
    description: "Revolution Day Special! 15% discount",
    durationDays: 1,
    backgroundColor: "#EF4444",
  },
  {
    name: "Sinai Liberation Day",
    type: "egyptian_holiday",
    gregorianDate: "04-25",
    discountPercentage: 15,
    icon: "flag",
    description: "Sinai Liberation Day! 15% off all services",
    durationDays: 1,
    backgroundColor: "#EF4444",
  },
  {
    name: "October War Victory",
    type: "egyptian_holiday",
    gregorianDate: "10-06",
    discountPercentage: 20,
    icon: "flag",
    description: "October Victory Day! Special 20% discount",
    durationDays: 1,
    backgroundColor: "#EF4444",
  },
  {
    name: "Egyptian National Day",
    type: "egyptian_holiday",
    gregorianDate: "07-23",
    discountPercentage: 20,
    icon: "flag",
    description: "Happy National Day! 20% off to celebrate Egypt",
    durationDays: 1,
    backgroundColor: "#EF4444",
  },
];

export const birthdayOffer: Omit<EventDate, "gregorianDate" | "islamicMonth" | "islamicDay"> = {
  name: "Your Birthday",
  type: "birthday",
  discountPercentage: 30,
  icon: "cake",
  description: "Happy Birthday! Enjoy 30% off as our gift to you",
  durationDays: 7,
  backgroundColor: "#F59E0B",
};
