export type SubscriptionPlan = {
  id: string;
  title: string;
  duration: string;
  basePrice: number;
  deliveryFee: number;
  discount: number;
  finalPrice: number;
  savings?: number;
  icon: "weekly" | "monthly" | "quarterly" | "biannual" | "yearly" | "student" | "couples" | "mothers" | "family";
  popular?: boolean;
  badge?: string;
  pieces: number;
  pickupsPerWeek: number;
  features: string[];
  bgColor: string;
  textColor: string;
  accentColor: string;
  gradient: string[];
  iconBg: string;
};

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: "weekly",
    title: "Weekly Plan",
    duration: "1 Week",
    basePrice: 150,
    deliveryFee: 30,
    discount: 0,
    finalPrice: 180,
    icon: "weekly",
    pieces: 10,
    pickupsPerWeek: 1,
    features: ["10 garment pieces", "1 pickup/week", "Standard ironing"],
    bgColor: "#E8F5E9",
    textColor: "#1B5E20",
    accentColor: "#4CAF50",
    gradient: ["#4CAF50", "#66BB6A"],
    iconBg: "rgba(255, 255, 255, 0.25)",
    badge: "STARTER",
  },
  {
    id: "monthly",
    title: "1 Month",
    duration: "30 Days",
    basePrice: 650,
    deliveryFee: 100,
    discount: 10,
    finalPrice: 675,
    savings: 75,
    icon: "monthly",
    popular: true,
    badge: "MOST POPULAR",
    pieces: 50,
    pickupsPerWeek: 2,
    features: ["50 garment pieces", "2 pickups/week", "Premium ironing", "Priority support"],
    bgColor: "#E3F2FD",
    textColor: "#0D47A1",
    accentColor: "#2196F3",
    gradient: ["#2196F3", "#42A5F5"],
    iconBg: "rgba(255, 255, 255, 0.25)",
  },
  {
    id: "3months",
    title: "3 Months",
    duration: "90 Days",
    basePrice: 2000,
    deliveryFee: 250,
    discount: 15,
    finalPrice: 1913,
    savings: 337,
    icon: "quarterly",
    badge: "BEST VALUE",
    pieces: 180,
    pickupsPerWeek: 3,
    features: ["180 garment pieces", "3 pickups/week", "Premium ironing & steaming", "Dedicated support", "Free stain removal"],
    bgColor: "#FFF3E0",
    textColor: "#E65100",
    accentColor: "#FF9800",
    gradient: ["#FF9800", "#FFB74D"],
    iconBg: "rgba(255, 255, 255, 0.25)",
  },
  {
    id: "6months",
    title: "6 Months",
    duration: "180 Days",
    basePrice: 4000,
    deliveryFee: 450,
    discount: 20,
    finalPrice: 3560,
    savings: 890,
    icon: "biannual",
    badge: "PREMIUM",
    pieces: 400,
    pickupsPerWeek: 4,
    features: ["400 garment pieces", "4 pickups/week", "Premium service", "VIP support", "Free alterations", "Quality guarantee"],
    bgColor: "#F3E5F5",
    textColor: "#4A148C",
    accentColor: "#9C27B0",
    gradient: ["#9C27B0", "#BA68C8"],
    iconBg: "rgba(255, 255, 255, 0.25)",
  },
  {
    id: "yearly",
    title: "1 Year",
    duration: "365 Days",
    basePrice: 8000,
    deliveryFee: 800,
    discount: 25,
    finalPrice: 6600,
    savings: 2200,
    icon: "yearly",
    badge: "ULTIMATE SAVER",
    pieces: 1000,
    pickupsPerWeek: 5,
    features: ["1000 garment pieces", "5 pickups/week", "Luxury service", "Concierge support", "All services included"],
    bgColor: "#FBE9E7",
    textColor: "#BF360C",
    accentColor: "#FF5722",
    gradient: ["#FF5722", "#FF7043"],
    iconBg: "rgba(255, 255, 255, 0.25)",
  },
  {
    id: "student",
    title: "Student Package",
    duration: "30 Days",
    basePrice: 400,
    deliveryFee: 50,
    discount: 30,
    finalPrice: 315,
    savings: 135,
    icon: "student",
    badge: "STUDENT SAVER",
    pieces: 35,
    pickupsPerWeek: 2,
    features: [
      "35 garment pieces",
      "2 pickups/week",
      "30% student discount",
      "Free study-wear care",
      "Exam week priority",
      "Weekend express service",
      "Budget-friendly pricing",
      "Flexible scheduling"
    ],
    bgColor: "#E8F4F8",
    textColor: "#0B4F6C",
    accentColor: "#00A8E8",
    gradient: ["#00A8E8", "#00BCD4"],
    iconBg: "rgba(255, 255, 255, 0.25)",
  },
  {
    id: "couples",
    title: "Couples Package",
    duration: "30 Days",
    basePrice: 1200,
    deliveryFee: 150,
    discount: 20,
    finalPrice: 1080,
    savings: 270,
    icon: "couples",
    badge: "PERFECT PAIR",
    pieces: 100,
    pickupsPerWeek: 3,
    features: [
      "100 garment pieces (shared)",
      "3 pickups/week",
      "20% couple discount",
      "His & Hers premium care",
      "Matching scent options",
      "Date night express",
      "Dual pickup locations",
      "Anniversary bonus",
      "Free gift wrapping"
    ],
    bgColor: "#FCE4EC",
    textColor: "#880E4F",
    accentColor: "#E91E63",
    gradient: ["#E91E63", "#F06292"],
    iconBg: "rgba(255, 255, 255, 0.25)",
  },
  {
    id: "mothers",
    title: "Mothers Package",
    duration: "30 Days",
    basePrice: 900,
    deliveryFee: 100,
    discount: 25,
    finalPrice: 750,
    savings: 250,
    icon: "mothers",
    badge: "MOM'S SPECIAL",
    pieces: 80,
    pickupsPerWeek: 4,
    features: [
      "80 garment pieces",
      "4 pickups/week",
      "25% mom discount",
      "Kids clothes included",
      "Stain removal expert",
      "Baby-safe detergents",
      "Same-day service",
      "Flexible timing",
      "Emergency wash option",
      "Family care bundle"
    ],
    bgColor: "#FFF8E1",
    textColor: "#F57F17",
    accentColor: "#FFC107",
    gradient: ["#FFC107", "#FFD54F"],
    iconBg: "rgba(255, 255, 255, 0.25)",
  },
  {
    id: "family",
    title: "Family Plan",
    duration: "30 Days",
    basePrice: 1400,
    deliveryFee: 150,
    discount: 22,
    finalPrice: 1209,
    savings: 341,
    icon: "family",
    badge: "FAMILY CHOICE",
    pieces: 120,
    pickupsPerWeek: 4,
    features: [
      "120 garment pieces for the whole family",
      "4 pickups/week",
      "22% family discount",
      "All ages clothing care",
      "Mixed garment handling",
      "Priority family service",
      "Separate packaging per member",
      "Extended care options",
      "Weekend availability",
      "Emergency service included"
    ],
    bgColor: "#E8F5F9",
    textColor: "#01579B",
    accentColor: "#03A9F4",
    gradient: ["#03A9F4", "#4FC3F7"],
    iconBg: "rgba(255, 255, 255, 0.25)",
  },
];

export const getPopularPlans = () => subscriptionPlans.filter(plan => plan.popular);

export const getPlanById = (id: string) => subscriptionPlans.find(plan => plan.id === id);

export const getHomePlans = () => [
  subscriptionPlans[0],
  subscriptionPlans[1],
  subscriptionPlans[4],
];
